using System.Collections.Generic;
using System.Text.Json.Serialization;
using WorldSimApp.Models;

namespace WorldSimApp.Models;

[JsonSerializable(typeof(GameState))]
[JsonSerializable(typeof(GameStatistics))]
[JsonSerializable(typeof(PlayerCountryData))]
[JsonSerializable(typeof(Country))]
[JsonSerializable(typeof(CountryData))]
[JsonSerializable(typeof(SimulationEvent))]
[JsonSerializable(typeof(DecisionEvent))]
[JsonSerializable(typeof(DecisionOption))]
[JsonSerializable(typeof(DecisionType))]
[JsonSerializable(typeof(GameSettings))]
[JsonSerializable(typeof(War))]
[JsonSerializable(typeof(WarStatus))]
[JsonSerializable(typeof(WarResult))]
[JsonSerializable(typeof(Territory))]
[JsonSerializable(typeof(InternationalOrganization))]
[JsonSerializable(typeof(OrganizationData))]
[JsonSerializable(typeof(Resource))]
[JsonSerializable(typeof(CountryResource))]
[JsonSerializable(typeof(TradeRoute))]
[JsonSerializable(typeof(CountryResourceData))]
[JsonSerializable(typeof(Party))]
[JsonSerializable(typeof(PartyIdeology))]
[JsonSerializable(typeof(Election))]
[JsonSerializable(typeof(Treaty))]
[JsonSerializable(typeof(TradeAgreement))]
[JsonSerializable(typeof(Sanction))]
[JsonSerializable(typeof(SanctionType))]
[JsonSerializable(typeof(EconomicCycle))]
[JsonSerializable(typeof(EconomicCyclePhase))]
[JsonSerializable(typeof(ChainEvent))]
[JsonSerializable(typeof(Technology))]
[JsonSerializable(typeof(ClimateEvent))]
[JsonSerializable(typeof(CountryMemory))]
[JsonSerializable(typeof(GeopoliticalFactor))]
[JsonSerializable(typeof(DiplomaticAction))]
[JsonSerializable(typeof(PendingPolicy))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(double))]
[JsonSerializable(typeof(long))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(List<double>))]
[JsonSerializable(typeof(List<Country>))]
[JsonSerializable(typeof(List<SimulationEvent>))]
[JsonSerializable(typeof(List<DecisionEvent>))]
[JsonSerializable(typeof(List<War>))]
[JsonSerializable(typeof(List<Territory>))]
[JsonSerializable(typeof(List<InternationalOrganization>))]
[JsonSerializable(typeof(List<Resource>))]
[JsonSerializable(typeof(List<CountryResource>))]
[JsonSerializable(typeof(List<TradeRoute>))]
[JsonSerializable(typeof(List<Party>))]
[JsonSerializable(typeof(List<Election>))]
[JsonSerializable(typeof(List<Treaty>))]
[JsonSerializable(typeof(List<TradeAgreement>))]
[JsonSerializable(typeof(List<Sanction>))]
[JsonSerializable(typeof(List<ChainEvent>))]
[JsonSerializable(typeof(List<Technology>))]
[JsonSerializable(typeof(List<ClimateEvent>))]
[JsonSerializable(typeof(Dictionary<string, double>))]
[JsonSerializable(typeof(Dictionary<string, int>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(Dictionary<string, List<double>>))]
public partial class WorldSimJsonContext : JsonSerializerContext
{
}
